### PR TITLE
add travis, remove categories from _oasis

### PR DESCRIPTION
**Pull request by hannesm**
could someone with rights on travis please enable mirage-entropy builds? (@avsm @samoht)

### CODE REVIEW

**Comment by avsm** [comment]
done. Might need a dummy push to this branch.

**Comment by hannesm** [comment]
cool, building!

**Comment by pqwy** [comment]
Weeee!

**Comment by samoht** [comment]
well doesn't seem to build very well :-)

```
#=== ERROR while installing mirage-entropy-xen.0.3.0 ==========================#
# opam-version 1.2.1
# os           linux
# command      make
# path         /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-22981-0c525f.env
# stdout-file  /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-22981-0c525f.out
# stderr-file  /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-22981-0c525f.err
### stdout ###
# ocaml setup.ml -build 
# ocamlfind ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -O3 -ccopt '-std=c99' -ccopt -Wall -ccopt -Wpedantic -ccopt '-isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen -isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.6/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-ocaml/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/travis/.opam/system/include  ' -ccopt -mrdrnd -ccopt -mrdseed -c lib/entropy_cpu_xen_stubs.c
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -O3 -ccopt '-std=c99' -ccopt -Wall -ccopt -Wpedantic -ccopt '-isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen -isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.6/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-ocaml/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/travis/.opam/system/include  ' -ccopt -mrdrnd -ccopt -mrdseed -c lib/entropy_cpu_xen_stubs.c
# cc1: error: unrecognized command line option ‘-mrdseed’
# cc1: error: unrecognized command line option ‘-Wpedantic’
# Command exited with code 2.
```

**Comment by pqwy** [comment]
Yeah, noted. Travis is running an ancient gcc, and now the grim alternatives are entropy and everything that depends on it failing tests, disabling the Broadwell-specific instruction, or sordid postconf trickery peppered with some ASM replacing the intrinsic.

:cry:

**Comment by mor1** [comment]
Add a `.travis-ci.sh` script that upgrades `gcc` before fetching @samoht 's Travis/OPAM script?

eg., https://github.com/travis-ci/travis-ci/issues/1379

**Comment by samoht** [comment]
yea, that's a good idea.

**Comment by hannesm** [comment]
on which platforms / C compilers do we expect this to work then? is `>= gcc-4.7` (or `clang ??` 3.5/3.6 has it at least) reasonable? or will people try it with gcc-4.4 and complain?

**Comment by avsm** [comment]
I think we do need to stop supporting older GCCs -- this will break CentOS 6 and Ubuntu LTS, but clear configure script instructions requesting a more modern GCC should be fine.  /cc @djs55

**Comment by MagnusS** [comment]
Would be nice if we could still support Ubuntu 14.04 LTS. The gcc version is 4.8.2 in 14.04.2

**Comment by pqwy** [comment]
GCC 4.8.x is good enough. And I agree, many people seem to use the latest Ubuntu LTS and it makes all the sense in the world to support it.

The problem is that Travis is running Ubuntu 12.04 atm, but we'll figure that one out...

**Comment by hannesm** [comment]
@pqwy see #19, the underlying problem is that there isn't a binutils (`> 2.22`) on `ubuntu precise` available (and 2.22 does not have `rdseed` mnemonics)

**Comment by pqwy** [comment]
@hannesm I know, I know. Scouring the web for PPAs as we spe^H^H^Hwrite.

Btw this is tested with clang 3.6.0 and gcc 4.9.2. According to the docs, gcc >= 4.8.x is needed; for clang/llvm, the patch adding support is 2 years old, but I cannot find the precise version this was first released in.

**Pull request merged**
