### PR TITLE
upgrade to gcc 4.8 before executing travis script

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by samoht** [comment]
errr...
```
#=== ERROR while installing mirage-entropy-xen.0.3.0 ==========================#
# opam-version 1.2.1
# os           linux
# command      make
# path         /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-23570-0c525f.env
# stdout-file  /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-23570-0c525f.out
# stderr-file  /home/travis/.opam/system/build/mirage-entropy-xen.0.3.0/mirage-entropy-xen-23570-0c525f.err
### stdout ###
# ocaml setup.ml -build 
# ocamlfind ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -O3 -ccopt '-std=c99' -ccopt -Wall -ccopt -Wpedantic -ccopt '-isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen -isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-ocaml/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/travis/.opam/system/include  ' -ccopt -mrdrnd -ccopt -mrdseed -c lib/entropy_cpu_xen_stubs.c
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -O3 -ccopt '-std=c99' -ccopt -Wall -ccopt -Wpedantic -ccopt '-isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen -isystem/home/travis/.opam/system/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-ocaml/include -I/home/travis/.opam/system/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/travis/.opam/system/include  ' -ccopt -mrdrnd -ccopt -mrdseed -c lib/entropy_cpu_xen_stubs.c
# /tmp/ccBOSDSh.s: Assembler messages:
# /tmp/ccBOSDSh.s:22: Error: no such instruction: `rdseed %rax'
```

**Comment by hannesm** [comment]
yes, but why?

**Comment by hannesm** [comment]
well, binutils (`as`) is still too old, and I fail to find any `.deb` at launchpad for ubuntu-12 which is newer than a binutils 2012 release (instructions were added https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=e2e1fcde622f2f6cedfd7fb6615aa6e136f21dec)

**Comment by pqwy** [comment]
@hannesm According to the PPA [list](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test), there *is* a newer release of binutils in there, but unlike gcc, branches are not separate packages. Could you try changing:

`sudo apt-get -qq install gcc-4.8 binutils`

to:

`sudo apt-get -qq install gcc-4.8 binutils=2.25-2ubuntu2`

or:

`sudo apt-get -qq install gcc-4.8 'binutils=2.25-2ubuntu2~14.10'`

... please?

**Comment by pqwy** [comment]
... or even `'binutils=2.25-*'`. `apt-get` has various ways to denote version constraints, but I don't have a single Debian-oid handy to read the man page...

**Comment by pqwy** [comment]
Nope. And without a glob?

**Comment by hannesm** [comment]
so `binutils=2.25-2ubuntu2` and `binutils=2.25*` didn't work so far, trying `binutils=2.25-2ubuntu2~14.10` at the moment

**Comment by pqwy** [comment]
Nailed it!

nailing it

**Comment by dsheets** [comment]
[Isenheim Altarpiece](http://en.wikipedia.org/wiki/Isenheim_Altarpiece) if you were wondering.

**Pull request merged**
